version: '3.8'
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq -C config/sidekiq.yml
    container_name: sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1 # Redis service URL
volumes:
  redis_data:
    driver: local
  mongodb_data:
